version: '2'
services:
    ttw-mongo:
        container_name: ttw-mongo
        image: mongo:3.2.11
        volumes:
            - ttw-db:/data/db
    ttw-node:
        container_name: ttw-node
        image: nicolaslefebvre/ttw:latest
        depends_on:
            - ttw-mongo
        ports:
            - "80:8000"
        environment:
            NODE_ENV: production
            TTW_MONGODB_URL: mongodb://ttw-mongo:27017/ttw
        env_file:
            - ./secrets.env

volumes:
    ttw-db:
        driver: local
