version: '2'
services:
    ttw-mongo:
        container_name: ttw-mongo
        image: mongo
        volumes:
            - ttw-db:/data/db
    ttw-node:
        container_name: ttw-node
        image: nicolaslefebvre/ttw:alpha
        depends_on:
            - ttw-mongo
        ports:
            - "80:8000"
        environment:
            NODE_ENV: production
            TTW_MONGODB_URL: mongodb://ttw-mongo:27017/ttw
            TTW_GOOGLE_DISTANCE_MATRIX_API_KEY: 
            TTW_PLACES_JSON_STRING:

volumes:
    ttw-db:
        driver: local
